### ISSUE TITLE
Verlinkung euer Lösung im offiziellen Hauptrepository?

### ISSUE THREAD

**Issue by jonico** [nicosc77/pandemie#1]
Hallo @nicosc77,

bis jetzt haben wir eure tolle Einsendung noch nicht in https://github.com/informatiCup/informatiCup2020/tree/master/github-sonderpreis gesehen, wollt ihr einen pull-request stellen?

Liebe Grüße und frohe Ostern

@jonico

:octocat: ❤️

**Comment by nicosc77** [comment]
Erledigt 👍
